force-app/main/default/objects/Account/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Version_Date__c.field-meta.xml
<CustomField>
    <fullName>Version_Date__c</fullName>
    <label>Version Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Version_History__c.field-meta.xml
<CustomField>
    <fullName>Version_History__c</fullName>
    <label>Version History</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Version_Snapshot__c.field-meta.xml
<CustomField>
    <fullName>Version_Snapshot__c</fullName>
    <label>Version Snapshot</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/versioning/classes/RecordVersionaryTest.cls
@isTest
public with sharing class RecordVersionaryTest {
    @isTest
    public static void testIncreaseVersion() {
        Account account = new Account();
        account.Name = 'test account';
        insert account;

        SObject theRecord = (Database.query('SELECT ' + VersioningAction.toString4AllFieldsOfSObject('Account', null) + ' FROM Account WHERE Id = \'' + account.Id + '\''))[0]; 
        
        RecordVersionary.Wrapper currentVersionData = new RecordVersionary.Wrapper();
        currentVersionData.version = (Decimal)theRecord.get('Version__c');
        currentVersionData.versionDate = (Datetime)theRecord.get('Version_Date__c');
        currentVersionData.versionSnapshot = (String)theRecord.get('Version_Snapshot__c');
        currentVersionData.versionHistory = (String)theRecord.get('Version_History__c');
        currentVersionData.allFieldsRecord = theRecord;

        RecordVersionary.Wrapper newVersionData = RecordVersionary.increaseVersion(currentVersionData);
    }
}